"use client";

import { useState } from "react";
import { respondSalaryOffer } from "@/lib/salary-offers/actions";
import type { Database } from "@/types/database";
type Offer = Database["public"]["Tables"]["salary_offers"]["Row"] & { salonName: string };
const REASONS = [["workdays","勤務日数・休日"],["guarantee_period","保証期間"],["role","役割・業務範囲"],["performance_basis","実績の評価方法"],["other","その他"]] as const;
export function StylistOfferCard({ offer }: { offer: Offer }) {
  const [reason,setReason]=useState<typeof REASONS[number][0]>("performance_basis"); const [note,setNote]=useState(""); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState<string|null>(null); const [consult,setConsult]=useState(false);
  async function answer(response:"accepted"|"revision_requested"|"declined") { setBusy(true); setMsg(null); const r=await respondSalaryOffer({offerId:offer.id,response,reason:response==="revision_requested"?reason:null,note:response==="revision_requested"?(note||null):null}); setBusy(false); setMsg(r.success?"回答を送信しました。":r.error); }
  return <article className="rounded-2xl border border-line bg-surface p-5"><p className="eyebrow mb-1">実績オファー</p><h3 className="font-serif text-lg font-bold text-ink">{offer.salonName}</h3><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-surface2 p-2"><p className="text-[10px] text-sub">月額保証</p><p className="mt-1 text-[13px] font-bold">{offer.monthly_guarantee.toLocaleString()}円</p></div><div className="rounded-lg bg-surface2 p-2"><p className="text-[10px] text-sub">実績加算</p><p className="mt-1 text-[13px] font-bold">{offer.performance_addition.toLocaleString()}円</p></div><div className="rounded-lg bg-surface2 p-2"><p className="text-[10px] text-sub">保証期間</p><p className="mt-1 text-[13px] font-bold">{offer.guarantee_months}か月</p></div></div>
  {offer.performance_addition > 0 && <div className="mt-3 rounded-lg border border-line bg-surface2 p-3"><p className="text-[10px] font-semibold text-sub">支給条件</p><p className="mt-1 text-[12px] leading-relaxed text-charcoal">{offer.performance_condition ?? "未記載"}</p></div>}
  {offer.salon_message&&<p className="mt-3 text-[12px] leading-relaxed text-charcoal">{offer.salon_message}</p>}<p className="mt-3 text-[10px] text-sub">これは面談前の条件提示であり、雇用契約の確定ではありません。</p>
  {offer.status==="pending"&&<>{consult?<div className="mt-4"><select value={reason} onChange={(e)=>setReason(e.target.value as typeof reason)} className="w-full rounded-lg border border-line px-3 py-2 text-[11px]">{REASONS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><textarea value={note} onChange={(e)=>setNote(e.target.value)} maxLength={500} placeholder="相談したい内容（任意）" className="mt-2 min-h-16 w-full rounded-lg border border-line px-3 py-2 text-[11px]"/><button disabled={busy} onClick={()=>answer("revision_requested")} className="mt-2 w-full rounded-full bg-ink py-2 text-[11px] font-bold text-surface">相談内容を送る</button></div>:<div className="mt-4 grid grid-cols-3 gap-2"><button disabled={busy} onClick={()=>answer("accepted")} className="rounded-full bg-[#285B45] py-2 text-[11px] font-bold text-white">承諾</button><button disabled={busy} onClick={()=>setConsult(true)} className="rounded-full border border-line py-2 text-[11px]">条件を相談</button><button disabled={busy} onClick={()=>answer("declined")} className="rounded-full border border-line py-2 text-[11px] text-sub">辞退</button></div>}</>}
  {offer.status!=="pending"&&<p className="mt-3 text-[11px] font-semibold text-sub">回答済み: {{accepted:"承諾",revision_requested:"条件を相談",declined:"辞退",withdrawn:"取り下げ"}[offer.status]??offer.status}</p>}{msg&&<p className="mt-2 text-[11px] text-charcoal">{msg}</p>}</article>;
}

